import { Product } from "./types";

export const CATEGORIES = ["Dairy", "Snacks", "Fruits", "Vegetables", "Bakery", "Beverages"];

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Fresh Milk (1L)",
    price: 60,
    category: "Dairy",
    image: "https://images.unsplash.com/photo-1550583724-125581f77833?auto=format&fit=crop&w=800&q=80",
    description: "Farm fresh cow milk, delivered daily.",
    isSubscriptionEligible: true,
    isInstantEligible: true,
    estimatedDeliveryTime: "15 mins",
  },
  {
    id: "p2",
    name: "Brown Bread",
    price: 45,
    category: "Bakery",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    description: "Whole wheat brown bread, freshly baked.",
    isSubscriptionEligible: true,
    isInstantEligible: true,
    estimatedDeliveryTime: "10 mins",
  },
  {
    id: "p3",
    name: "Organic Eggs (6pcs)",
    price: 55,
    category: "Dairy",
    image: "https://images.unsplash.com/photo-1516746157585-fa5f4532902a?auto=format&fit=crop&w=800&q=80",
    description: "High protein organic eggs.",
    isSubscriptionEligible: true,
    isInstantEligible: true,
    estimatedDeliveryTime: "12 mins",
  },
  {
    id: "p4",
    name: "Banana (1kg)",
    price: 50,
    category: "Fruits",
    image: "https://images.unsplash.com/photo-1571771894821-ad990241274d?auto=format&fit=crop&w=800&q=80",
    description: "Sweet and ripe bananas.",
    isSubscriptionEligible: true,
    isInstantEligible: true,
    estimatedDeliveryTime: "20 mins",
  },
  {
    id: "p5",
    name: "Potato (1kg)",
    price: 30,
    category: "Vegetables",
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80",
    description: "Freshly harvested potatoes.",
    isSubscriptionEligible: true,
    isInstantEligible: true,
    estimatedDeliveryTime: "18 mins",
  },
  {
    id: "p6",
    name: "Tomato (500g)",
    price: 25,
    category: "Vegetables",
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80",
    description: "Red and juicy tomatoes.",
    isSubscriptionEligible: true,
    isInstantEligible: true,
    estimatedDeliveryTime: "15 mins",
  },
  {
    id: "p7",
    name: "Lays Classic",
    price: 20,
    category: "Snacks",
    image: "https://images.unsplash.com/photo-1566478431375-7042f1f4464d?auto=format&fit=crop&w=800&q=80",
    description: "Crispy potato chips.",
    isSubscriptionEligible: false,
    isInstantEligible: true,
    estimatedDeliveryTime: "10 mins",
  },
  {
    id: "p8",
    name: "Coca Cola (500ml)",
    price: 40,
    category: "Beverages",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80",
    description: "Refreshing soft drink.",
    isSubscriptionEligible: false,
    isInstantEligible: true,
    estimatedDeliveryTime: "12 mins",
  },
  {
    id: "p9",
    name: "Apples (500g)",
    price: 120,
    category: "Fruits",
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6bcd6?auto=format&fit=crop&w=800&q=80",
    description: "Crispy red apples.",
    isSubscriptionEligible: true,
    isInstantEligible: true,
    estimatedDeliveryTime: "15 mins",
  },
  {
    id: "p10",
    name: "Carrot (500g)",
    price: 35,
    category: "Vegetables",
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=800&q=80",
    description: "Fresh orange carrots.",
    isSubscriptionEligible: true,
    isInstantEligible: true,
    estimatedDeliveryTime: "12 mins",
  },
];
